---
apiVersion: networking.k8s.io/v1
kind: Ingress  
metadata:
  name: spring-app-ing
  namespace: app2
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: tls-secret
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-app-svc
            port: 
              number: 80


